backend/apps/catalog/urls.py
from django.urls import path

from .views import CatalogPageView, CategoryDetailView, CatalogOrderFormView, send_order


urlpatterns = [
    path('', CatalogPageView.as_view(), name="catalog"),
    path('get-order-form/<slug:slug>/', CatalogOrderFormView.as_view(), name="order_form"),
    path('order', send_order, name="send_order"),
    path('category/<slug:slug>/', CategoryDetailView.as_view(), name="category"),
]

backend/core/urls.py
from django.http import HttpResponse
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from .sitemap import StaticViewSitemap, CategoriesSitemap

sitemaps = {
    "static": StaticViewSitemap,
    "categories": CategoriesSitemap,
}


def health_check(request):
    return HttpResponse("OK")


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('apps.home.urls')),
    path("health/", health_check),
    path('about/', include('apps.about.urls')),
    path('delivery/', include('apps.delivery.urls')),
    path('catalog/', include('apps.catalog.urls')),
    path('contacts/', include('apps.contacts.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path(
        'sitemap.xml',
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/apps/catalog/models.py
from django.db import models
from django.urls import reverse

from ckeditor_uploader.fields import RichTextUploadingField

from .managers import CategoryManager
from core.abstract_models import TimeStampedModel, SeoModel


class Category(TimeStampedModel, SeoModel):
    """Модель категорії."""
    enabled = models.BooleanField('Увімкнено', default=True, help_text='Чи відображати на веб-сайті дану категорію?')
    title = models.CharField('Назва', max_length=255)
    slug = models.SlugField(
        'Slug (для url)',
        max_length=255,
    )
    price = models.TextField(
        'Вартість',
        blank=True
    )
    description = RichTextUploadingField('Опис')
    weight = models.PositiveIntegerField(
        'Вага',
        default=1000,
        help_text='Чим більша вага, тим далі елемент буде у списку на сторінці'
    )

    objects = CategoryManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('category', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Категорія'
        verbose_name_plural = 'Категорії'


class CategoryImage(TimeStampedModel):
    """Модель зображення категорії."""
    category = models.ForeignKey(Category, verbose_name='Категорія', on_delete=models.CASCADE, default=None)
    image = models.ImageField(
        'Зображення',
        upload_to="uploads/%Y/%m/%d/",
        help_text='Зображення буде автоматично приведено до розміру 800*800 пікселей при виводі на сторінці категорії.'
    )
    weight = models.PositiveIntegerField(
        'Вага',
        default=1000,
        help_text='Чим більша вага, тим далі елемент буде у списку на сторінці'
    )

    class Meta:
        verbose_name = 'Зображення категорії'
        verbose_name_plural = 'Зображення категорії'


class CategoryProperty(TimeStampedModel):
    """Модель характеристики категорії."""
    category = models.ForeignKey(Category, verbose_name='Категорія', on_delete=models.CASCADE, default=None)
    key = models.CharField('Назва', max_length=255)
    value = models.TextField('Значення')
    weight = models.PositiveIntegerField(
        'Вага',
        default=1000,
        help_text='Чим більша вага, тим далі елемент буде у списку на сторінці'
    )

    def __str__(self):
        return self.key

    class Meta:
        verbose_name = 'Характеристика категорії'
        verbose_name_plural = 'Характеристики категорії'


class CatalogPage(SeoModel, TimeStampedModel):
    description = RichTextUploadingField('Опис', blank=True)

    def __str__(self):
        return 'Сторінка списку категорій'

    class Meta:
        verbose_name = 'Зміст сторінки списку категорій'
        verbose_name_plural = 'Зміст сторінки списку категорій'

backend/apps/catalog/forms.py
import requests
from django import forms
from django.conf import settings
from django.core.exceptions import ValidationError

from apps.contacts.services import contacts_get_telegram_chat_id
from .models import Category, CategoryProperty
from .services import category_get_by_slug


class CategoryModelForm(forms.ModelForm):

    class Meta:
        model = Category
        exclude = ()
        widgets = {
            'price': forms.Textarea(attrs={'rows': 2, 'cols': 33})
        }


class CategoryPropertyModelForm(forms.ModelForm):

    class Meta:
        model = CategoryProperty
        exclude = ()
        widgets = {
            'value': forms.Textarea(attrs={'rows': 1, 'cols': 33})
        }


class OrderForm(forms.Form):
    action = forms.CharField(max_length=19)
    norobot = forms.CharField(max_length=100, required=False)
    category_slug = forms.CharField(max_length=100)
    contact_name = forms.CharField(max_length=100)
    contact_phone = forms.CharField(max_length=100)
    contact_message = forms.CharField(max_length=1024)

    def clean_action(self):
        value = self.cleaned_data.get('action')
        if value != 'order_submit':
            raise ValidationError("Недопустимое значение для action.")
        return value

    def clean_norobot(self):
        value = self.cleaned_data.get('norobot')
        if value:
            raise ValidationError("Поле norobot должно быть пустым.")
        return value

    def clean_category_slug(self):
        value = self.cleaned_data.get('category_slug')
        if not category_get_by_slug(value):
            raise ValidationError("Поле category_slug содержит неверное значение.")
        return value

    def send_to_telegram(self):
        token = settings.TELEGRAM_TOKEN
        chat_id = contacts_get_telegram_chat_id()
        if chat_id:
            category = category_get_by_slug(self.cleaned_data['category_slug'])
            text = (
                f"<b>Замовлення</b>\n\n"
                f"Категорія: {category.title}\n"
                f"Ім'я: {self.cleaned_data['contact_name']}\n"
                f"Телефон: {self.cleaned_data['contact_phone']}\n"
                f"Повідомлення: {self.cleaned_data['contact_message']}"
            )

            url = f"https://api.telegram.org/bot{token}/sendMessage"
            payload = {
                'chat_id': chat_id,
                'text': text,
                'parse_mode': 'HTML',
            }

            response = requests.post(url, data=payload)
            response.raise_for_status()

backend/apps/catalog/views.py
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.views.generic.base import TemplateView
from django.views.generic import DetailView
from django.http import Http404, HttpResponse

from .forms import OrderForm
from .models import CatalogPage, Category
from .services import category_get_all_items_enabled_qs


class CatalogPageView(TemplateView):
    """Відображає сторінку списку категорій."""
    template_name = 'catalog/index/index.html'

    def get_context_data(self, **kwargs):
        context = super(CatalogPageView, self).get_context_data(**kwargs)
        context['page'] = CatalogPage.objects.first()
        context['categories'] = category_get_all_items_enabled_qs()
        if not context['page']:
            raise Http404("CatalogPage does not exist.")

        return context


class CategoryDetailView(DetailView):
    model = Category
    template_name = 'catalog/category/index.html'
    queryset = category_get_all_items_enabled_qs()


class CatalogOrderFormView(TemplateView):
    template_name = 'catalog/category/_partials/form.html'


@require_POST
@csrf_exempt
def send_order(request):
    form = OrderForm(request.POST)
    if form.is_valid():
        form.send_to_telegram()
        return HttpResponse('{:success:}')
    print(form.errors)
    return HttpResponse('{:err:required:}')

backend/apps/catalog/templates/catalog/category/_partials/breadcrumbs.html
{% load static %}

<div class="section jarallax text-center-xs overlay-dark overlay-opacity-7 text-white">

    <!-- jarallax image -->
    <img class="jarallax-img" src="{% static 'assets/images/endoscopie_reconditionne_1.webp' %}" alt="...">


    <div class="container h-100">

        <div class="d-table">
            <div class="d-table-cell align-middle">

                <h1>{% if category.meta_h1 %}{{ category.meta_h1 }}{% else %}{{ category.title }}{% endif %}</h1>

                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb small justify-content-md-start justify-content-center">
                        <li class="breadcrumb-item"><a class="text-white" href="{% url 'home' %}">Головна</a></li>
                        <li class="breadcrumb-item"><a class="text-white" href="{% url 'catalog' %}">Каталог</a></li>
                        <li class="breadcrumb-item text-white active" aria-current="page">{{ category.title }}</li>
                    </ol>
                </nav>

            </div>
        </div>

    </div>
</div>

backend/apps/catalog/templates/catalog/category/_partials/form.html
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabelSm">Запит замовлення</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>

<div class="modal-body mb-2">
    <div class="px-4">

        <!--
          CONTACT FORM : AJAX [TESTED|WORKING AS IT IS]

            Plugin required: SOW Ajax Forms

            In order to work as ajax form, SOW Ajax Forms should be available/enabled
            Else, SOW Form Validation plugin is used.
            If none of them are available, normal submit is used and you can remove:
              .js-ajax
              .bs-validate
              novalidate
              any data-ajax-*
              any data-error-*

            ** Remove data-error-toast-* for no error toast notifications




          Ajax will control success/fail alerts according to server response:

            1. unexpected error:    if server response is this string: {:err:unexpected:}
            2. mising mandatory:    if server response is this string: {:err:required:}
            3. success:         if server response is this string: {:success:}

            data-ajax-control-alerts="true"
            data-ajax-control-alert-succes="#contactSuccess"
            data-ajax-control-alert-unexpected="#contactErrorUnexpected"
            data-ajax-control-alert-mandaroty="#contactErrorMandatory"

          +++++++++++++++++++++++++++++++++++++++++++++++++++++++
            WORKING CONTACT! Edit your php/config.inc.php
          +++++++++++++++++++++++++++++++++++++++++++++++++++++++
        -->
        <form novalidate
              action="{% url 'send_order' %}"
              method="POST"

              data-ajax-container="#ajax_dd_contact_response_container"
              data-ajax-update-url="false"
              data-ajax-show-loading-icon="true"
              data-ajax-callback-function=""
              data-error-scroll-up="false"

              data-ajax-control-alerts="true"
              data-ajax-control-alert-succes="#contactSuccess"
              data-ajax-control-alert-unexpected="#contactErrorUnexpected"
              data-ajax-control-alert-mandaroty="#contactErrorMandatory"

              data-error-toast-text="<i class='fi fi-circle-spin fi-spin float-start'></i> Будь ласка, заповніть усі обов'язкові поля!"
              data-error-toast-delay="2000"
              data-error-toast-position="bottom-center"

              class="bs-validate js-ajax">


            <!-- 1.
              optional, hidden action for your backend

              PHP Basic Example
              if($_POST['action'] == 'contact_form_submit') {
                ... send message
              }
            -->
            <input type="hidden" name="action" value="order_submit" tabindex="-1">
            <!-- -->


            <!-- 2.
              A very small optional trick (using .hide class instead of type="hidden") for some low spam robots.
              If this is not empty, the process should stop. A normal user/visitor should not be able to see this field.

              PHP Basic Example
              if($_POST['norobot'] != '') {
                exit;
              }
            -->
            <input type="text" name="norobot" value="" class="hide" tabindex="-1">
            <!-- -->
            <input type="text" name="category_slug" value="{{ slug }}" class="hide" tabindex="-1">

            <div class="form-floating mb-3">
                <input required placeholder="ПІБ" id="contact_name" name="contact_name" type="text"
                       class="form-control">
                <label for="contact_name">ПІБ</label>
            </div>

            <div class="form-floating mb-3">
                <input required placeholder="Телефон" id="contact_phone" name="contact_phone" type="text"
                       class="form-control">
                <label for="contact_phone">Телефон</label>
            </div>

            <div class="form-floating mb-3">
                <textarea required placeholder="Повідомлення" id="contact_message" name="contact_message"
                          class="form-control" rows="3" style="min-height:120px"></textarea>
                <label for="contact_message">Повідомлення</label>
            </div>

            <!--
              Server detailed error
              !ONLY! If debug is enabled!
              Else, shown ony "Server Error!"
            -->
            <div id="ajax_dd_contact_response_container"></div>

            <!-- {:err:unexpected:} internal server error -->
            <div id="contactErrorUnexpected" class="hide alert alert-danger p-3">
                Unexpected Error!
            </div>

            <!-- {:err:required:} mandatory fields -->
            <div id="contactErrorMandatory" class="hide alert alert-danger p-3">
                Будь ласка, перевірте чи заповнили ви усі обов'язкові поля.
            </div>

            <!-- {:success:} message sent -->
            <div id="contactSuccess" class="hide alert alert-success p-3">
                Дякуємо за ваше повідомлення. Невдовзі ми надамо вам відповідь.
            </div>


            <button type="submit" class="btn btn-primary w-100">
                <i class="fi fi-envelope"></i>
                Відправити
            </button>

        </form>
        <!-- /CONTACT FORM : AJAX -->

    </div>
</div>

backend/apps/catalog/templates/catalog/category/_partials/gallery.html
{% load thumbnail %}

<div class="col-lg-6 order-1 mb-4">

    <!--
        Thumbnails are initialized first!
        Order changed using .order-* classes
    -->
    <div class="card p-1 h-100">
        <div class="row">
            {% if not category.categoryimage_set.all %}
                <div class="col-12">
                    <div class="py-2 px-4">
                    <img class="img-fluid rounded"
                         data-src="https://placehold.co/800?text=No+Image"
                         src="https://placehold.co/800?text=No+Image"
                         alt="No image">
                    </div>
                </div>
            {% else %}
                <!-- thumbnail slider -->
                <div class="col-12 order-2">

                    <div id="swiper_secondary" class="swiper-container swiper-thumbs mt-3"
                         data-swiper='{
                                                    "slidesPerView": 3,
                                                    "spaceBetween": 3,
                                                    "autoplay": false,
                                                    "loop": false,
                                                    "zoom": false,
                                                    "effect": "slide",
                                                    "pagination": null,
                                                    "watchSlidesVisibility": true,
                                                    "watchSlidesProgress": true,
                                                    "loopedSlides": 1,
                                                    "thumbs": {
                                                        "slideThumbActiveClass": "bg-light"
                                                    },
                                                    "breakpoints": {
                                                        "768": 	{ "slidesPerView": "5" }
                                                    }
                                                }'>

                        <div class="swiper-wrapper text-center">

                            {% for image in category.categoryimage_set.all %}
                            <div class="swiper-slide p-2 rounded cursor-pointer">
                                <img height="80" class="bg-suprime rounded"
                                     src="{{ image.image.url|thumbnail_url:'category_xs' }}"
                                     alt="...">
                            </div>
                            {% endfor %}

                        </div>

                    </div>

                </div>
                <!-- /thumbnail slider (hidden on mobile) -->


                <!-- primary slider -->
                <div class="col-12 order-1">

                    <div id="swiper_primary" class="swiper-container swiper-preloader swiper-white mx-auto"
                         data-swiper-link="swiper_secondary"
                         data-swiper='{
                                                    "slidesPerView": 1,
                                                    "spaceBetween": 0,
                                                    "autoplay": false,
                                                    "loop": true,
                                                    "zoom": true,
                                                    "effect": "slide",
                                                    "loopedSlides": 1,
                                                    "breakpoints": {
                                                        "920": 	{ "slidesPerView": "1" }
                                                    }
                                                }'>
                        <div class="swiper-wrapper text-center">

                            {% for image in category.categoryimage_set.all %}
                            <div class="swiper-slide">
                                <div class="swiper-zoom-container">
                                    <img class="{% if not forloop.first %}lazy {% endif %}bg-suprime img-fluid rounded"

                                         sizes="(max-width: 768px) 100vw"
                                         src="{{ image.image.url|thumbnail_url:'category' }}"
                                         alt="..." style="max-height: 600px;">
                                </div>
                            </div>
                            {% endfor %}

                        </div>

                        <!-- Left|Right Arrows -->
                        <div class="swiper-button-next rounded-circle shadow-xs d-none d-md-block"></div>
                        <div class="swiper-button-prev rounded-circle shadow-xs d-none d-md-block"></div>

                    </div>
                    <!-- /primary slider -->

                </div>
            {% endif %}
        </div>
    </div>

</div>

backend/apps/catalog/templates/catalog/category/_partials/options.html
<div class="col-lg-6 order-2 mb-4 card p-3-xs p-xl-5">
    {% if category.price %}
        <h3 class="fw-bold">Вартість:</h3>
        <div class="fs-6 mb-4">
            <span class="fw-bolder text-teal-900">{{ category.price|safe|linebreaksbr }}</span>
        </div>
    {% endif %}

    <div class="mb-5">
        <a href="#"
           data-href="{% url 'order_form' slug=category.slug %}"
           data-ajax-modal-size="modal-md"
           data-ajax-modal-centered="true"
           data-ajax-modal-callback-function=""
           class="js-ajax-modal btn btn-lg btn-primary w-100 fs-5">
            <i class="fi fi-cart-2"></i>
            Замовити
        </a>
    </div>

    <div class="mb-2">
        <h2 class="h3 fw-bold">Характеристики:</h2>
    </div>

    <div class="table-responsive">
        <table class="table table-striped">
            <tbody>
            {% for item in category.categoryproperty_set.all %}
                <tr>
                    <td class="text-muted w-50">{{ item.key }}</td>
                    <td>{{ item.value|safe|linebreaksbr }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>